spring.datasource.username=root
spring.datasource.password=VhrNqozZukhFyuQeGfUmdslLuirZTQiR
spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:52158/railway

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amgothk50@gmail.com
spring.mail.password=jqte uzbq wnqn cwtb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true